service: gettogether

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev

functions: 
  helloworld:
    handler: src/functions/helloworld.handler
    events:
      - http:
          path: api/helloworld/{name}
          method: get

resources:
  Resources:
    GetTogethersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gettogethers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST